# Generated by Django 3.1.3 on 2020-11-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_boardmodel_readmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='readMember',
        ),
    ]
